### ISSUE TITLE
Fix Linux

### ISSUE THREAD

**Issue by XandrCopyrighted** [XandrCopyrighted/Cazic#5]

**Comment by WilliamAnimate** [comment]
it freezes and i don't want to help you fix it :skull:

https://github.com/XandrCopyrighted/Cazic/assets/75321465/00abb9bf-6bcb-41c8-b3ff-1d2d92720afd

**Comment by XandrCopyrighted** [comment]
![image](https://github.com/XandrCopyrighted/Cazic/assets/111686716/6d592801-d2fd-4aa1-972e-517285c9a6d5)

**Comment by XandrCopyrighted** [comment]
make sure to install `gst-plugins-good` !
