### ISSUE TITLE
App is active in the background, not displayed on screen.

### ISSUE THREAD

**Issue by XandrCopyrighted** [XandrCopyrighted/Cazic#9]
![image](https://github.com/XandrCopyrighted/Cazic/assets/111686716/ca8aa76d-dff6-4e61-ad2b-7730c969a926)

**Comment by WilliamAnimate** [comment]
aw shit my bad

i was trying to fix conflicts and github said it'd push to `main`. i thought it meant main for my fork but no, main for this repo

fix this locally:
uncomment lines https://github.com/XandrCopyrighted/Cazic/blob/main/src/main.rs#L37-L42
and comment lines https://github.com/XandrCopyrighted/Cazic/blob/main/src/main.rs#L32-L36
